http_log.view_log:
    resource: '@HttpLogBundle/Resources/config/routing/view-log.yaml'
    prefix: /admin/http-log
echo:
    path: '{path}'
    controller: App\Controller\DefaultController::echoAction
    requirements:
      path: ".*"
