version: '3'

services:
  web:
    container_name: httplog.web
    image: nginx
    ports: ["80:80"]
    volumes:
      - ./web/nginx.conf:/etc/nginx/nginx.conf
      - ./web/conf.d/host.conf:/etc/nginx/conf.d/host.conf
      - "../:/var/local:rw"
      - 'code:/var/code'
    networks: [httplog.net]

  php:
    container_name: httplog.php
    build:
      context: ..
      dockerfile: compose/php/Dockerfile
    volumes:
      - "../:/var/local/:rw"
      - "code:/var/code"
    networks: [httplog.net]

networks:
  httplog.net: ~

volumes:
  code:
